name = "javascript_dom_parser"
version = "1.0.0"
target = "javascript"
description = "Bindings to the JavaScript DOMParser API"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "javascript-dom-parser" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "DOMParser", href = "https://developer.mozilla.org/en-US/docs/Web/API/DOMParser" },
]

[javascript]
runtime = "deno"

[javascript.deno]
allow_read = ["gleam.toml", "test", "birdie_snapshots"]
allow_write = ["birdie_snapshots"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.1.0 and < 2.0.0"
pprint = ">= 1.0.1 and < 2.0.0"
